### ISSUE TITLE
Add full scope of stories projects to PivotalTracker

### ISSUE THREAD

**Issue by bboe** [scalableinternetservices/Seal-Team-CSIL#3]
Pivotal tracker currently appears to have three major features:
- Add / edit providers
- Add / edit food/drinks deals
- Create users

Having this functionality is a fantastic start. I'm assuming you've yet to add the full scope of features that your web service will provide. Can you please add stories for all the features you'd like to add prior to Tuesday's class?

**Comment by bboe** [comment]
Can I please get an update on this issue?

**Comment by camsb** [comment]
Should the stories be broad features we would like to have or more specifics?

**Comment by bboe** [comment]
If you want to start broad that's fine, but in some way everything you may like to accomplish should be in Pivotal. There should be no need to create new feature ideas part way through the quarter (of course you can) but your team should be set up with some final product in mind.

The goal is for me to ensure your project is ambitious enough feature wise to satisfy the complexity needed for this class.
